//
//package com.qashqai.model;
//
//import java.time.LocalDate;
//
//import javax.persistence.Column;
//import javax.persistence.Entity;
//import javax.persistence.GeneratedValue;
//import javax.persistence.GenerationType;
//import javax.persistence.Id;
//import javax.persistence.ManyToMany;
//
//import javax.persistence.JoinColumn;
//
////vendor table
//@Entity
//public class Vendor {
//	// table columns
//
//	// vendor id(primary key, autogenerated)
//	@Id
//	@GeneratedValue(strategy = GenerationType.IDENTITY)
//	@Column(name = "vendorId")
//	private Integer vendorId;
//
//	// vendor name
//	@Column(name = "vendorName", nullable = false, length = 60)
//	private String vendorName;
//
//	// vendor type
//	@Column(name = "vendorType", nullable = false, length = 60)
//	private String vendorType;
//
//	// valid from date
//	@Column(name = "validFrom")
//	private LocalDate dteValidFrom;
//
//	// valid to date
//	@Column(name = "validTo")
//	private LocalDate dteValidTo;
//
//	// address
//	@Column(name = "address", nullable = false, length = 60)
//	private String address;
//
//	// checking status of vendor
//	private boolean isActive = true;
//	@ManyToMany
//	@JoinColumn(name = "assetId", insertable = false, updatable = false)
//	private Asset asset;
//
//	// record creation date
//	@Column(name = "dteCreatedAt")
//	private LocalDate dteCreatedAt;
//
//	// record modification date
//	@Column(name = "dteModifiedAt")
//	private LocalDate dteModifiedAt;
//
//	// record deletion date
//	@Column(name = "dteDeletedAt")
//	private LocalDate dteDeletedAt;
//
//	public Integer getVendorId() {
//		return vendorId;
//	}
//
//	public void setVendorId(Integer vendorId) {
//		this.vendorId = vendorId;
//	}
//
//	public String getVendorName() {
//		return vendorName;
//	}
//
//	public void setVendorName(String vendorName) {
//		this.vendorName = vendorName;
//	}
//
//	public String getVendorType() {
//		return vendorType;
//	}
//
//	public void setVendorType(String vendorType) {
//		this.vendorType = vendorType;
//	}
//
//	public LocalDate getDteValidFrom() {
//		return dteValidFrom;
//	}
//
//	public void setDteValidFrom(LocalDate dteValidFrom) {
//		this.dteValidFrom = dteValidFrom;
//	}
//
//	public LocalDate getDteValidTo() {
//		return dteValidTo;
//	}
//
//	public void setDteValidTo(LocalDate dteValidTo) {
//		this.dteValidTo = dteValidTo;
//	}
//
//	public String getAddress() {
//		return address;
//	}
//
//	public void setAddress(String address) {
//		this.address = address;
//	}
//
//	public boolean isActive() {
//		return isActive;
//	}
//
//	public void setActive(boolean isActive) {
//		this.isActive = isActive;
//	}
//
//	public Asset getAsset() {
//		return asset;
//	}
//
//	public void setAsset(Asset asset) {
//		this.asset = asset;
//	}
//
//	public LocalDate getDteCreatedAt() {
//		return dteCreatedAt;
//	}
//
//	public void setDteCreatedAt(LocalDate dteCreatedAt) {
//		this.dteCreatedAt = dteCreatedAt;
//	}
//
//	public LocalDate getDteModifiedAt() {
//		return dteModifiedAt;
//	}
//
//	public void setDteModifiedAt(LocalDate dteModifiedAt) {
//		this.dteModifiedAt = dteModifiedAt;
//	}
//
//	public LocalDate getDteDeletedAt() {
//		return dteDeletedAt;
//	}
//
//	public void setDteDeletedAt(LocalDate dteDeletedAt) {
//		this.dteDeletedAt = dteDeletedAt;
//	}
//
//}
