
package com.qashqai.model;

import java.time.LocalDate;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;

import javax.persistence.JoinColumn;

//vendor table
@Entity
public class Vendors {
	// table columns

	// vendor id(primary key, autogenerated)
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "vendorId")
	private Integer vendorId;

	// vendor name
	@Column(name = "vendorName", nullable = false, length = 60)
	private String vendorName;

	// vendor type
	@Column(name = "vendorType", nullable = false, length = 60)
	private String vendorType;

	// valid from date
	@Column(name = "validFrom")
	private LocalDate dteValidFrom;

	// valid to date
	@Column(name = "validTo")
	private LocalDate dteValidTo;

	// address
	@Column(name = "address", nullable = false, length = 60)
	private String address;

	// checking status of vendor
	private boolean isActive = true;
	@ManyToMany
	@JoinColumn(name = "assetId", insertable = false, updatable = false)
	private Asset asset;

	// record creation date
	@Column(name = "dteCreatedAt")
	private LocalDate dteCreatedAt;

	// record modification date
	@Column(name = "dteModifiedAt")
	private LocalDate dteModifiedAt;

	// record deletion date
	@Column(name = "dteDeletedAt")
	private LocalDate dteDeletedAt;

}
